### ISSUE TITLE
pdf file not found on windows

### ISSUE THREAD

**Issue by purpleleaf** [NoviceLive/pdfbookmark#1]
Using windows i obtain this error:

pdfmark -r "(?:CERTIFICAZIONE\ DI\ CUI\ ALL)"  "CU_2018.pdf"
ERROR: Unhandled Exception: [WinError 2] Impossibile trovare il file specificato
Traceback (most recent call last):
  File "c:\users\administrator.csc\appdata\local\programs\python\python37\lib\site-packages\pycliprog\argparse\__init__.py", line 58, in start
    self.main()
  File "c:\users\administrator.csc\appdata\local\programs\python\python37\lib\site-packages\pdfmark\__main__.py", line 50, in main
    bookmark_title = parse_text(extract_text(self.args.pdf, i), self.args.regex)
  File "c:\users\administrator.csc\appdata\local\programs\python\python37\lib\site-packages\pdfmark\__main__.py", line 127, in extract_text
    return subprocess.check_output(args).decode('utf-8')
  File "c:\users\administrator.csc\appdata\local\programs\python\python37\lib\subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "c:\users\administrator.csc\appdata\local\programs\python\python37\lib\subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "c:\users\administrator.csc\appdata\local\programs\python\python37\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "c:\users\administrator.csc\appdata\local\programs\python\python37\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] Impossibile trovare il file specificato

the pdf file was in the directory i was working, but also using absolute path does not solve the problem.

**Comment by NoviceLive** [comment]
Thanks for reporting.
It's most likely that you do not have the program ``pdftotext`` installed on your system.

You could get a copy of ``pdftotext`` for Windows at [Xpdf command line tools](https://www.xpdfreader.com/download.html).
Put them on your ``PATH`` and then try again.

FYI, there are also third-party builds of [Poppler for Windows](http://blog.alivate.com.au/poppler-windows/).

Let me know if that works.
